wolf_Creek_kennel_project/urls.py
from django.contrib import admin
from django.urls import path
from dogs import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('sires/', views.sires, name="sires"),
    path('dams/', views.dams, name="dams"),
    path('nursery/', views.nursery, name="nursery"),
    path('gallery/', views.gallery, name="gallery"),
    path('aboutTheKennel/', views.about_the_kennel, name="about_the_kennel"),
    path('contactUs/', views.contact_us, name="contact_us"),
    path('contactUs/<int:pk>/', views.contact_us_about_puppy, name="contact_us_about_puppy"),
    path('contactUs/send/', views.send_contact_us, name="send_contact_us"),
    path('faq/', views.faq, name="faq"),
    path('available_puppy/<int:pk>/', views.puppy_detail_sale, name="available_puppy_detail"),
    path('puppy/<int:pk>/', views.puppy_detail, name="puppy_detail"),
    path('dog/<int:pk>/', views.adult_dog_detail, name="adult_dog_detail"),
    path('litter/<int:pk>/', views.litter_detail, name="litter_detail"),
    path('newsletter/', views.add_email_to_newsletter, name="add_email_to_newsletter"),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

dogs/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError

class Litter(models.Model):
    title = models.CharField(max_length=500)
    mother = models.ForeignKey("Dog", related_name="mother", on_delete=models.CASCADE)
    father = models.ForeignKey("Dog", related_name="father", on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    main_image = models.ImageField(upload_to='images/', null=True, blank=True)
    coming_soon = models.BooleanField(default=False)
    due_date = models.DateField(null=True, blank=True, default=None)

    def __str__(self):
        return self.title

    def clean(self):
        super().clean()
        if not self.coming_soon and self.due_date is not None:
            raise ValidationError('Due date is only allowed if coming soon is true.')

class Dog(models.Model):
    litter = models.ForeignKey(Litter, related_name="dogs", on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=500)
    show_name = models.BooleanField()
    description = models.TextField(null=True, blank=True)
    birthday = models.DateField()
    available_for_sale = models.BooleanField()
    puppy = models.BooleanField() 
    sexes = (('M', 'Male'), ('F', 'Female'))
    sex = models.CharField(max_length=1, choices=sexes)
    breeds = (('EB', 'English Bulldog'), ('FB', 'French Bulldog'))
    breed = models.CharField(max_length=2, choices=breeds, default='EB')
    pedigree = models.ImageField(upload_to='images/', null=True, blank=True)
    main_image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.name

class Dog_Image(models.Model):
    dog = models.ForeignKey(Dog, related_name="dog_images", on_delete=models.CASCADE)  
    name = models.CharField(max_length=500) 
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return f"{self.dog.name}: {self.name}"

class Litter_Image(models.Model):
    puppy_litter = models.ForeignKey(Litter, related_name="litter_images", on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return f"{self.puppy_litter.title}: {self.name}"

class Dog_Video(models.Model):
    dog = models.ForeignKey(Dog, related_name="dog_videos", on_delete=models.CASCADE) 
    name = models.CharField(max_length=500)
    video = models.FileField(upload_to='videos/', validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv'])])

    def __str__(self):
        return f"{self.dog.name}: {self.name}"

class Litter_Video(models.Model):
    puppy_litter = models.ForeignKey(Litter, related_name="litter_videos", on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    video = models.FileField(upload_to='videos/', validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv'])])

    def __str__(self):
        return f"{self.puppy_litter.name}: {self.name}"

class Misc_Image(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name

class Misc_Video(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    video = models.FileField(upload_to='videos/', validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv'])])

    def __str__(self):
        return self.name

class FAQ(models.Model):
    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return self.question

class Email(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

templates/FAQ.html
{% extends 'base.html' %}
{% block content%} 
{% load static %}
    <div class="heading">
        <h1>Frequently Asked Questions</h1>
    </div>
    <div class=faq>
     {% for faq in faqs %}
        <h3>{{ faq.question }}</h3>
        <p>{{ faq.answer }}</p>
     {% endfor %}
    </div>
{% endblock %}

templates/about_the_kennel.html
{% extends 'base.html' %}
{% block content%} 
{% load static %} 
    <div class="heading"> 
        <h1>About the Kennel</h1>
    </div>
    <div id="about-the-kennel">
        <div v-if="screenSize === 'large'">
        <img id="about-the-kennel-hero" src="{% static 'images/bulldog.jpg' %}" alt="Bulldog">
        </div>
        <div id="about-the-kennel-text">
            <h3>Background Information</h3>

            <p>We are a family from Oklahoma that is committed to raising high quality English and French Bulldogs. We
                are passionate about these breeds and are dedicated to ensuring our high quality bulldogs are
                living happy and healthy lives.<br><br>
                ​All of our bulldogs are AKC Registered and come with a one year health guarantee! We would
                love to hear from you if you are interested in one of our pups!</p>

            <div id=about-the-kennel-hero-container v-if="screenSize === 'small'">
                <img id="about-the-kennel-hero" src="{% static 'images/bulldog.jpg' %}" alt="Bulldog">
            </div>

            <h3>Meet the family</h3>

            <p>Our love for bulldogs started at an early age. At the age of 16, Kyle saved up the money to gift
                Jenny her first English bulldog. The rest is history! We were hooked to this breed and their
                loving, yet playful demeanor. Several years, and three kids later we are still dedicated to sharing
                our love of this breed with others!</p>

        </div>
        
    </div>
{% endblock %}

templates/adult_dog_detail.html
{% extends 'base.html' %}
{% block content%} 
{% load static %}
    <div class="heading">
        {% if dog.sex == "M" %}
            <h1>Sires</h1>
        {% else%}
            <h1>Dams</h1>
        {% endif %}
    </div>
    <div class="dog-detail-container">
        <div>
            {% if dog.main_image.url != None %}
                <img class="main-image" src="{{dog.main_image.url}}" alt="Adult Dog">
            {% endif %}
        </div>
        <div class="dog-detail-text">
            {% if dog.show_name %}
                <h2 class="detail-name">{{dog.name}}</h2>
            {% endif %}
            <p>{{dog.get_sex_display}}</p>           
            <p>{{dog.get_breed_display}}</p>
            <p>Age: {{age}}</p>
        </div>
    </div>
    {% if dog.description != None %}
                <p class="description">{{dog.description}}</p>
    {% endif %}
    <div class="image-carousel">
        {% if dog.dog_images.all|length > 4  %}
            <div @click="imageCarouselLeft()" class="div-click">
                <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
            </div>
        {% endif %}
            {% for image in dog.dog_images.all %}       
                <div class="image-carousel-image">
                    <img src="{{ image.image.url }}" alt="Additional puppy photo">
                </div>
            {% endfor %}
        {% if dog.dog_images.all|length > 4 %}
            <div @click="imageCarouselRight()" class="div-click">
                <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/adult_dogs.html
{% extends 'base.html' %}
{% block content%} 
{% load static %}
        {% with adult_dogs|first as first_dog%}
            {% if first_dog.sex == "M" %}
            <div class="heading">
                <h1>Sires</h1>
            </div>
            {% else %}
            <div class="heading">
                <h1>Dams</h1>
            </div>
            {% endif %}
        {% endwith %}

        <div class="card-container">
            <div v-if="screenSize == 'small'">
                {% if adult_dogs|length > 1%}
                    <div @click="carouselLeft('general')" class="div-click">
                        <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
                    </div>
                {% endif %}
            </div>
            <div v-else>
                {% if adult_dogs|length > 3%}
                    <div @click="carouselLeft('general')" class="div-click">
                        <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
                    </div>
                {% endif %}
            </div>
            {% for dog in adult_dogs %}
                <div class="card"><a href="{% url 'adult_dog_detail' dog.pk %}">
                    {% if dog.main_image.url != None %}
                        <img src="{{ dog.main_image.url }}" alt="Dog">
                    {% endif %}
                    {% if dog.show_name %}
                        <p>{{ dog.name }}</p>
                    {% endif %}
                    <p>{{dog.get_sex_display}}</p>
                    <p>{{dog.get_breed_display}}</p>
                    {% for age in ages %}
                        {% if dog.pk == age.pk %}
                            <p>Age: {{age.age}}</p>
                        {% endif %}
                    {% endfor %}
                </a></div>
            {% endfor %}
            <div v-if="screenSize == 'small'">
                {% if adult_dogs|length > 1%}
                <div @click="carouselRight('general')" class="div-click">
                    <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
                </div>
            {% endif %}
            </div>
            <div v-else>
                {% if adult_dogs|length > 3%}
                <div @click="carouselRight('general')" class="div-click">
                    <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
                </div>
            {% endif %}
            </div>           
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles-l.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles-ml.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles-m.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles-s.css' %}">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐶</text></svg>">
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/gsap.min.js"></script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script> {% endcomment %}
    <title>Wolf Creek Bulldogs</title>
</head>
<body>
    <div id="app" v-cloak>
        <div id="logo-container">
            {% comment %} <a href={% url 'index' %}><img id="logo" src="{% static '/images/logo.png' %}" alt="logo"></a> {% endcomment %}
            <a href={% url 'index' %}><img id="logo" src="{% static 'images/logo2.png' %}" alt="logo"></a>
            <a href={% url 'index' %}><h1 id="logo-text">Wol<span id="offset">f Creek Bull</span>dogs</h1></a>
        </div>
        <nav>   
            <div id="nav1">  
                <a class="nav-item" href={% url 'sires' %}>Sires</a>
                <p class="nav-divider">|</p>
                <a class="nav-item" href={% url 'dams' %}>Dams</a>
                <p class="nav-divider">|</p>
                <a class="nav-item" href={% url 'nursery' %}>Nursery</a>
                <p class="nav-divider">|</p>
                <a class="nav-item" href={% url 'gallery' %}>Gallery</a>
            </div>   
            <div id="nav2">                  
                <a class="nav-item" href={% url 'about_the_kennel' %}>About the Kennel</a>
                <p class="nav-divider">|</p>
                <a class="nav-item" href={% url 'contact_us' %}>Contact Us</a>
                <p class="nav-divider">|</p>
                <a class="nav-item" href={% url 'faq' %}>FAQ</a>
            </div>
            <div id="phone-heading">
                {% comment %} Javascript will input the heading here when it identifies a small screen {% endcomment %}
                <h1>[[phoneHeading]]</h1>
            </div>
            <ul class="nav-menu">
                <li class="nav-item">
                    <a href={% url 'sires' %} class="nav-link">Sires</a>
                </li>
                <li class="nav-item">
                    <a href={% url 'dams' %} class="nav-link">Dams</a>
                </li>
                <li class="nav-item">
                    <a href={% url 'nursery' %} class="nav-link">Nursery</a>
                </li>
                <li class="nav-item">
                    <a href={% url 'gallery' %} class="nav-link">Gallery</a>
                </li>
                <li class="nav-item">
                    <a href={% url 'about_the_kennel' %} class="nav-link">About the Kennel</a>
                </li>
                <li class="nav-item">
                    <a href={% url 'contact_us' %} class="nav-link">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a href={% url 'faq' %} class="nav-link">FAQ</a>
                </li>
            </ul>
            <div class="hamburger" @click="mobileMenu()">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
        <div id="block">
            {% block content%}
            {% endblock %}
        </div>
    </div>
    <footer id="footer">
        <div id="footer-text">
            <p>Wolf Creek Bulldogs</p>
            <p>Henryetta, Oklahoma</p>          
        </div>
        <a href="#"><img src="{% static 'images/facebook-logo.png' %}" alt="Follow us on Facebook"></a>
    </footer>

<!-- Import Ajax -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- Import Vue.js -->
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>

<!-- Import file.js -->
<script src="{% static 'scripts/app.js' %}"></script> 

<!-- Mount App -->
<script> const mountApp = app.mount('#app') </script>

</body>
</html>            

templates/contact_us.html
{% extends 'base.html' %}
{% block content%} 
{% load static %} 
    <div id="contact-us-page-container">
        <div id="contact-us-text">
            <h1>Contact us</h1>
            <p>Have a question?<br>We'd love to hear from you.<br>Please fill out the form with your inquiry.</p>
        </div>
        <form id="contact-us-form" action="{% url 'send_contact_us' %}" method="post">
            {% csrf_token %}
            <div id="contact-us-container">
                <div class="form-name">
                    <div class="form-first-name">
                        <label for="first-name">First Name*</label>
                        <input type="text" id="first-name" name="first_name">
                    </div>
                    <div class="form-last-name">
                        <label for="last-name">Last Name</label>
                        <input type="text" id="last-name" name="last_name">
                    </div>
                </div>
                <div class="form-email">
                    <label for="email">Email*</label>
                    <input type="email" id="email" name="email">
                </div>
                <div class="form-textbox">
                    {% if puppy != None %}
                        <label for="textbox">What can we help you with?*</label>
                        {% if puppy.show_name %} {% comment %} v-model="email.message {% endcomment %}
                            {% comment %} <div v-if="screenSize == 'small'">
                                <textarea id="textbox" rows="8" cols="30">Hi, I'm interested in purchasing {{puppy.name}}.</textarea>   
                            </div>
                            <div v-else>{% endcomment %}
                                <textarea name="message" id="textbox" rows="15" cols="50">Hi, I'm interested in purchasing {{puppy.name}}.</textarea>   
                            {% comment %} </div>                                     {% endcomment %}
                        {% else %}
                            {% comment %} <div v-if="screenSize == 'small'">
                                <textarea id="textbox" rows="8" cols="30">Hi, I'm interested in the purchasing the puppy from /puppies/{{puppy.pk}}.</textarea>   
                            </div>
                            <div v-else> {% endcomment %}
                                <textarea name="message" id="textbox" rows="15" cols="50">Hi, I'm interested in the purchasing the puppy from /puppies/{{puppy.pk}}.</textarea>   
                            {% comment %} </div>  {% endcomment %}
                        {% endif %}
                    {% else %}
                    {% comment %} <div v-if="screenSize == 'small'">
                        <textarea id="textbox" rows="8" cols="30"></textarea>   
                    </div>
                    <div v-else> {% endcomment %}
                        <label for="textbox">What can we help you with?*</label>
                        <textarea name="message" id="textbox" rows="15" cols="50"></textarea>   
                    {% comment %} </div>                                             {% endcomment %}
                    {% endif %}
                </div>
                {% comment %} <button type="button" type="submit" @click="sendEmail()">Submit</button> {% endcomment %}
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content%} 
{% load static %} 
    <div id="index-heading">
        <h1>Wolf Creek Bulldogs breeds quality English and French Bulldogs</h1>
        <h2>From the family pet to the award winning show dog.</h2>
    </div>
    <div class="card-container">
        <div v-if="screenSize == 'small'">
            {% if puppies_for_sale|length > 1%}
            <div @click="carouselLeft('general')" class="div-click">
                <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
            </div>
        {% endif %}
        </div>
        <div v-else>
            {% if puppies_for_sale|length > 3%}
            <div @click="carouselLeft('general')" class="div-click">
                <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
            </div>
        {% endif %}
        </div>     
        {% for puppy in puppies_for_sale %}
            {% if puppy.main_image.url != None %}
                <div class="card"><a href="{% url 'available_puppy_detail' puppy.pk %}">
                    <img src="{{ puppy.main_image.url }}" alt="Puppy for sale">
                    {% if puppy.show_name %}
                        <p>{{ puppy.name }}</p>
                    {% endif %}
                    <p>{{puppy.get_sex_display}}</p>
                    <p>{{puppy.get_breed_display}}</p>
                    <p>Born on {{puppy.birthday}}</p>
                    {% if puppy.available_for_sale %}
                        <p>Available</p>
                    {% endif %}
                </a></div>
            {% endif %}
        {% endfor %}
        <div v-if="screenSize == 'small'">
            {% if puppies_for_sale|length > 1%}
            <div @click="carouselRight('general')" class="div-click">
                <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
            </div>
        {% endif %}
        </div>
        <div v-else>
            {% if puppies_for_sale|length > 3%}
            <div @click="carouselRight('general')" class="div-click">
                <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
            </div>
        {% endif %}
        </div>     
    </div>
    <div id="newsletter">
        <h3>STAY IN THE KNOW</h3>
        <p>Want to know about upcomming litters, show results, and news about the kennel?</p>
        <p>Sign up for our newsletter.</p>
        <form id="newsletter-input-button" action="{% url 'add_email_to_newsletter' %}" method="post">
            {% csrf_token %}
            <input type="text" placeholder="Enter your email" name="email">
            <button class="b-button" type="submit">Subscribe</button>
        </form>
    </div>      
{% endblock %}

templates/litter_detail.html
{% extends 'base.html' %}
{% block content%} 
{% load static %} 
    <div class="heading">
        <h1>{{litter.title}}</h1>
    </div>

    <div class="individual-card-container">
        <div class="mother">
            <h2 class="subheader">Mother</h2>
            <div class="individual-card"><a href="{% url 'adult_dog_detail' litter.mother.pk %}">
                {% if litter.mother.main_image.url != None %}
                    <img src="{{ litter.mother.main_image.url }}" alt="Litter mother">
                {% endif %}
                {% if litter.mother.show_name %}
                    <p>{{ litter.mother.name }}</p>
                {% endif %}
                <p>{{litter.mother.get_sex_display}}</p>
                <p>{{litter.mother.get_breed_display}}</p>
            </a></div>
        </div>
        <div class="father">
            <h2 class="subheader">Father</h2>
            <div class="individual-card"><a href="{% url 'adult_dog_detail' litter.father.pk %}">
                {% if litter.father.main_image.url != None %}
                    <img src="{{ litter.father.main_image.url }}" alt="Litter father">
                {% endif %}
                {% if litter.father.show_name %}
                    <p>{{ litter.father.name }}</p>
                {% endif %}
                <p>{{litter.father.get_sex_display}}</p>
                <p>{{litter.father.get_breed_display}}</p>
            </a></div>
        </div>
    </div>

    {%if litter.dogs.all|length > 0 %}
        <h2 class="subheader">Puppies</h2>
    {% endif %}

    <div class="card-container">
        <div v-if="screenSize == 'small'">
            {% if litter.dogs.all|length > 1%}
                <div @click="carouselLeft('general')" class="div-click">
                    <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
                </div>
            {% endif %}
        </div>
        <div v-else>
            {% if litter.dogs.all|length > 3%}
                <div @click="carouselLeft('general')" class="div-click">
                    <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
                </div>
            {% endif %}
        </div>    
        {% for puppy in litter.dogs.all %}
            {% if puppy.main_image.url != None %}
                <div class="card">
                    {% if puppy.available_for_sale %}
                        <a href="{% url 'available_puppy_detail' puppy.pk %}">
                    {% else %}
                        <a href="{% url 'puppy_detail' puppy.pk %}">
                    {% endif %}
                    <img src="{{ puppy.main_image.url }}" alt="Puppy for sale">
                    {% if puppy.show_name %}
                        <p>{{ puppy.name }}</p>
                    {% endif %}
                    <p>{{puppy.get_sex_display}}</p>
                    <p>{{puppy.get_breed_display}}</p>
                    <p>Born on {{puppy.birthday}}</p>
                    {% if puppy.available_for_sale %}
                        <p>Available</p>
                    {% endif %}
                </a></div>
            {% endif %}
        {% endfor %}
        <div v-if="screenSize == 'small'">
            {% if litter.dogs.all|length > 1%}
                <div @click="carouselRight('general')" class="div-click">
                    <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
                </div>
            {% endif %}
        </div>
        <div v-else>
            {% if litter.dogs.all|length > 3%}
                <div @click="carouselRight('general')" class="div-click">
                    <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
                </div>
            {% endif %}
        </div>        
    </div>
        <div class="image-carousel">
            <div v-if="screenSize == 'small'">
                {% if litter.litter_images.all|length > 1  %}
                    <div @click="imageCarouselLeft()" class="div-click">
                        <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
                    </div>
                {% endif %}
            </div>
            <div v-else>
                {% if litter.litter_images.all|length > 4  %}
                    <div @click="imageCarouselLeft()" class="div-click">
                        <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
                    </div>
                {% endif %}
            </div>           
            {% for image in litter.litter_images.all %}       
                <div class="image-carousel-image">
                    <img src="{{ image.image.url }}" alt="Additional puppy photo">
                </div>
            {% endfor %}
            <div v-if="screenSize == 'small'">
                {% if litter.litter_images.all|length > 1 %}
                    <div @click="imageCarouselRight()" class="div-click">
                        <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
                    </div>
                {% endif %}
            </div>
            <div v-else>
                {% if litter.litter_images.all|length > 4 %}
                    <div @click="imageCarouselRight()" class="div-click">
                        <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
                    </div>
                {% endif %}
            </div>          
        </div>
    
    
{% endblock %}

templates/puppy_detail.html
{% extends 'base.html' %}
{% block content%} 
{% load static %}
    {% comment %} <div class="heading">
        <h1></h1>
    </div> {% endcomment %}
    
    <div class="dog-detail-container">
        <div>
            {% if puppy.main_image.url != None %}
                <img class="main-image" src="{{puppy.main_image.url}}" alt="Puppy">
            {% endif %}
        </div>
        <div class="dog-detail-text">
            {% if puppy.show_name %}
                <h2 class="detail-name">{{puppy.name}}</h2>
            {% endif %}
            <p>{{puppy.get_sex_display}}</p>           
            <p>{{puppy.get_breed_display}}</p>
            <p>Born on {{puppy.birthday}}</p>
        </div>
    </div>
    {% if puppy.description != None %}
        <p class="description">{{puppy.description}}</p>
    {% endif %}
    <div class="image-carousel">
        {% if puppy.dog_images.all|length > 4  %}
            <div @click="imageCarouselLeft()" class="div-click">
                <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
            </div>
        {% endif %}
            {% for image in puppy.dog_images.all %}       
                <div class="image-carousel-image">
                    <img src="{{ image.image.url }}" alt="Additional puppy photo">
                </div>
            {% endfor %}
        {% if puppy.dog_images.all|length > 4 %}
            <div @click="imageCarouselRight()" class="div-click">
                <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/puppy_detail_sale.html
{% extends 'base.html' %}
{% block content%} 
{% load static %}
    <div class="heading">
        <h1>This puppy is available!</h1>
    </div>
    <div class="dog-detail-container">
        <div>
            {% if puppy.main_image.url != None %}
                <img class="main-image" src="{{puppy.main_image.url}}" alt="Available Puppy">
            {% endif %}
        </div>
        <div class="dog-detail-text">
            {% if puppy.show_name %}
                <h2 class="detail-name">{{puppy.name}}</h2>
            {% endif %}
            <p>{{puppy.get_sex_display}}</p>           
            <p>{{puppy.get_breed_display}}</p>
            <p>Born on {{puppy.birthday}}</p>
            <a href="{% url 'contact_us_about_puppy' puppy.pk %}"><button class="a-button">Contact Us!</button></a>
        </div>
    </div>
    {% if puppy.description != None %}
        <p class="description">{{puppy.description}}</p>
    {% endif %}
    <div class="image-carousel">
        {% if puppy.dog_images.all|length > 4  %}
            <div @click="imageCarouselLeft()" class="div-click">
                <img src="{% static 'images/left-arrow.png' %}" alt="Left navigation arrow" class="left-arrow">
            </div>
        {% endif %}
            {% for image in puppy.dog_images.all %}       
                <div class="image-carousel-image">
                    <img src="{{ image.image.url }}" alt="Additional puppy photo">
                </div>
            {% endfor %}
        {% if puppy.dog_images.all|length > 4 %}
            <div @click="imageCarouselRight()" class="div-click">
                <img src="{% static 'images/right-arrow.png' %}" alt="Right navigation arrow" class="right-arrow">
            </div>
        {% endif %}
    </div>
{% endblock %}